### PR TITLE
Remove Codecov Patch

### PR DESCRIPTION
**Pull request by bisakhmondal**
This should work

### CODE REVIEW

**Comment by bisakhmondal** [comment]
@noob77777 how to remove `required` flag from this
image

Once it's merged the patch wouldn't popup just like

image

**Comment by noob77777** [comment]
> 
> 
> @noob77777 how to remove `required` flag from this
> image
> 
> Once it's merged the patch wouldn't popup just like
> 
> image

contact repo admin

**Comment by bisakhmondal** [comment]
hello Mr. @TheSYNcoder

**Comment by TheSYNcoder** [comment]
ha will remove this check

**Comment by bisakhmondal** [comment]
Cool. Squash it
@TheSYNcoder , @noob77777

**Pull request merged**
