### PR TITLE
grammar added

### PR DESCRIPTION
**Pull request by bisakhmondal**
# Grammer Template
## Description
Basic template

## Todo
 - [x] Add more tests
 - [x] Update grammar.g file
 - [x] make sure this works

### CODE REVIEW

**Comment by TheSYNcoder** [comment]
Checks failed man.

**Comment by bisakhmondal** [comment]
> Checks failed man.

Tham na bara

**Comment by TheSYNcoder** [comment]
> > Checks failed man.
> 
> Tham na bara

Language check failed
Also build checks failed.

**Comment by TheSYNcoder** [comment]
> > Checks failed man.
> 
> Tham na bara

Language check failed
Also build checks failed.

**Comment by bisakhmondal** [comment]
Don't khisti me later :))
```shell
/jucc/src/include/grammar/grammar.h:12:  For a static/global string constant, use a C style string instead: "const char EPSILON[]".  [runtime/string] [4]
Done processing /jucc/src/include/grammar/grammar.h
Total errors found: 1
```
Pseudo Culprit fixed

**Review by noob77777 — APPROVED** [review]
Quality code. Self approving :+1:

**Pull request merged**
